server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/identity"
    username: root
    password: root@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "EKZZLWUL71T3M6rhzs8qvxhZs3KsYVQeNmOL92pRdNvSeBo4S17sPBKAL3vfF81Z"


